apps/pedidos/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('item/<int:pedido>/', views.ItemCreateView.as_view(), name='pedido__add__item'),
    path('item/<int:pk>/atualizar/', views.ItemUpdateView.as_view(), name='pedido__atualiza__item'),
    path('item/<int:pk>/excluir/', views.ItemDeleteView.as_view(), name='pedido__excluir__item'),
    path('add/', views.PedidoCreateView.as_view(), name='pedido__cria'),
    path('<int:pk>/atualizar/', views.PedidoUpdateView.as_view(), name='pedido__atualiza'),
    path('<int:pk>/excluir/', views.PedidoDeleteView.as_view(), name='pedido__delete'),
    path('<int:pk>/fechar/', views.FecharPedidoView.as_view(), name='pedido__fechar'),
    path('<int:pk>/enviar/', views.EnviarPedidoView.as_view(), name='pedido__enviar'),
    path('<int:pk>/', views.PedidoDetailView.as_view(), name='pedido__detail'),
    path('fechados/', views.PedidoFechadoListView.as_view(), name='pedido__list__fechado'),
    path('enviados/', views.PedidoEnviadoListView.as_view(), name='pedido__list__enviado'),
    path('', views.PedidoCriadoListView.as_view(), name='pedido__list'),

]

apps/urls.py
from django.urls import path, include


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('clientes/', include('apps.clientes.urls')),
    path('produtos/', include('apps.produtos.urls')),
    path('pedidos/', include('apps.pedidos.urls')),
	path('login/', auth_views.LoginView.as_view(),{
		'template_name': 'registration/login.html',
		'redirect_authenticated_user': True,
	}, name='login'),
	path('logout/', auth_views.logout_then_login, name='logout'),
	path('trocarsenha/', auth_views.PasswordChangeView.as_view(
		template_name='auth/password_change.html'
	), name='password_change'),
	path('trocarsenha/sucesso/', auth_views.PasswordChangeDoneView.as_view(
		template_name='auth/password_change_done.html'
	), name='password_change_done'),
	path('esqueciminhasenha/', auth_views.PasswordResetView.as_view(
		template_name='auth/password_reset.html'
	), name='password_reset'),
	path('esqueciminhasenha/emailenviado/', auth_views.PasswordChangeDoneView.as_view(
		template_name='auth/password_reset_done.html'
	), name='password_reset_done'),
	path('esqueciminhasenha/novasenha/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})', auth_views.PasswordResetConfirmView.as_view(
		template_name='auth/password_reset_confirm.html'
	), name='password_reset_confirm'),
	path('esqueciminhasenha/feito/', auth_views.PasswordResetCompleteView.as_view(
		template_name='auth/password_reset_complete.html'
	), name='password_reset_complete'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
]

apps/pedidos/models.py
from django.db import models
from django.urls import reverse

class Item(models.Model):
    pedido = models.ForeignKey("pedidos.Pedido", verbose_name="Pedido", on_delete=models.CASCADE)
    produto = models.ForeignKey("produtos.Produto", verbose_name="Produto", on_delete=models.CASCADE)
    quantidade = models.DecimalField("Quantidade", max_digits=5, decimal_places=2)
    valor_base = models.DecimalField("Valor base", max_digits=10, decimal_places=2)
    subtotal = models.DecimalField("Subtotal", max_digits=10, decimal_places=2)

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Itens"
    
    def __str__(self):
        return "#" + str(self.pedido.id) + " - " + self.produto.nome
    
    def get_absolute_url(self):
        return reverse("pedido__detail", kwargs={"pk":self.pedido.pk})
 
    def get_update_url(self):
	    return reverse("pedido__atualiza__item", kwargs={"pk":self.pk})
 
    def get_delete_url(self):
    	return reverse("pedido__excluir__item", kwargs={"pk":self.pk})

    

class Pedido(models.Model):

    CRIADO = "CRD"
    FECHADO = "FCD"
    ENVIADO = "EVD"
    STATUSES = [
        (CRIADO, "Criado"),
        (FECHADO, "Fechado"),
        (ENVIADO, "Enviado"),
    ]

    cliente = models.ForeignKey("clientes.Cliente", verbose_name="Cliente", on_delete=models.CASCADE)
    data = models.DateField(verbose_name="Data")
    criado = models.DateField(auto_now_add=True, verbose_name="Criado em")
    total = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Total", default=0.0)
    status = models.CharField(max_length=5, verbose_name="Status", choices=STATUSES, default=CRIADO)
    itens = models.ManyToManyField("produtos.Produto", verbose_name="Itens", through="pedidos.Item")


    class Meta:
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"

    def __str__(self):
        return "#" + str(self.id) + " " + self.cliente.nome
    
    def get_itens(self):
        return Item.objects.filter(pedido=self.pk)
    
    def get_absolute_url(self):
    	return reverse("pedido__detail", kwargs={"pk":self.pk})
 
    def get_add_item_url(self):
        return reverse("pedido__add__item", kwargs={"pedido":self.pk})
 
    def get_update_url(self):
	    return reverse("pedido__atualiza", kwargs={"pk":self.pk})
 
    def get_delete_url(self):
    	return reverse("pedido__delete", kwargs={"pk":self.pk})
 
    def update_total(self):
        itens = self.get_itens()
        total = 0
        for item in itens:
            total = total + item.subtotal
        self.total = total
        self.save()

apps/produtos/models.py
from django.db import models
from django.urls import reverse


class Categoria(models.Model):

    nome = models.CharField(max_length=30, verbose_name="Nome")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return self.nome


class Produto(models.Model):

    LITROS = "L"
    GRAMAS = "GR"
    KILOS = "KG"
    UNIDADE = "UN"
    PECA = "PC"

    UNIDADES = [
        (LITROS, "Litros"),
        (GRAMAS, "Gramas"),
        (KILOS, "Kilos"),
        (UNIDADE, "Unidade"),
        (PECA, "Peça")
    ]

    nome = models.CharField(max_length=100, verbose_name="Nome")
    valor = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Valor")
    categoria = models.ForeignKey("produtos.Categoria", verbose_name="categoria", on_delete=models.CASCADE)
    unidade = models.CharField(max_length=2, choices=UNIDADES)

    class Meta:
        verbose_name = "Produto"
        verbose_name_plural = "Produtos"

    def __str__(self):
        return self.nome
    
    def get_absolute_url(self):
	    return reverse("produto__detail", kwargs={"pk":self.pk})
 
    def get_update_url(self):
	    return reverse("produto__atualiza", kwargs={"pk":self.pk})
 
    def get_delete_url(self):
	    return reverse("produto__delete", kwargs={"pk":self.pk})

apps/pedidos/forms.py
from django import forms

from .models import Pedido, Item

class PedidoForm(forms.ModelForm):

	class Meta:
		model = Pedido
		fields = [
			'cliente',
			'data',
			'total',
		]
  
class ItemForm(forms.ModelForm):
    
	class Meta:
		model = Item
		fields = [
			'produto',
			'quantidade',
		]

apps/pedidos/views.py
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import redirect, get_object_or_404

from .models import Pedido, Item
from .forms import PedidoForm, ItemForm

class PedidoCriadoListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    queryset = Pedido.objects.filter(status=Pedido.CRIADO)
    template_name = 'pedidos/pedido_list.html'
    paginate_by = 10
    
    def get_context_data(self):
        context = super().get_context_data()
        context['CRIADO'] = True
        return context
class PedidoFechadoListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    queryset = Pedido.objects.filter(status=Pedido.FECHADO)
    template_name = 'pedidos/pedido_list.html'
    paginate_by = 10
    
    def get_context_data(self):
        context = super().get_context_data()
        context['FECHADO'] = True
        return context
    
class PedidoEnviadoListView(LoginRequiredMixin, SuccessMessageMixin, ListView):
    queryset = Pedido.objects.filter(status=Pedido.ENVIADO)
    template_name = 'pedidos/pedido_list.html'
    paginate_by = 10
    
    def get_context_data(self):
        context = super().get_context_data()
        context['ENVIADO'] = True
        return context
    
class PodeModificarMixin(object):
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object(self.queryset)
        if self.object.status == Pedido.CRIADO:
            return super().dispatch(request, *args, **kwargs)
        messages.error(request, "Esse pedido não pode mais ser alterado")
        return redirect(self.object.get_absolute_url())
            
    
class PedidoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
	template_name = 'pedidos/pedido_form.html'
	model = Pedido
	form_class = PedidoForm
	success_message = 'Pedido adicionado com sucesso!'

class PedidoUpdateView(LoginRequiredMixin, SuccessMessageMixin, PodeModificarMixin, UpdateView):
	template_name = 'pedidos/pedido_form.html'
	model = Pedido
	form_class = PedidoForm
	success_message = 'Pedido atualizado com sucesso!'
 

    
class PedidoDetailView(LoginRequiredMixin, SuccessMessageMixin, DetailView):
    model = Pedido
    template_name = 'pedidos/pedido_detail.html'
    
    
class PedidoDeleteView(LoginRequiredMixin, SuccessMessageMixin, PodeModificarMixin, DeleteView):
    template_name = 'pedidos/pedido_delete.html'
    model = Pedido
    success_url = reverse_lazy('pedido__list')
    success_message = 'Pedido excluido com sucesso!'
    
class FecharPedidoView(View):
    
    def get(self, request, *args, **kwargs):
        pedido = get_object_or_404(Pedido, id=self.kwargs['pk'])
        return redirect(pedido.get_absolut_url())
    
    def post(self, request, *args, **kwargs):
        pedido = get_object_or_404(Pedido, id=self.kwargs['pk'])
        pedido.status = Pedido.FECHADO
        pedido.save()
        messages.success(self.request, "Pedido finalizado com sucesso")
        return redirect(pedido.get_absolute_url())
    
class EnviarPedidoView(View):
    
    def get(self, request, *args, **kwargs):
        pedido = get_object_or_404(Pedido, id=self.kwargs['pk'])
        return redirect(pedido.get_absolut_url())
    
    def post(self, request, *args, **kwargs):
        pedido = get_object_or_404(Pedido, id=self.kwargs['pk'])
        pedido.status = Pedido.ENVIADO
        pedido.save()
        messages.success(self.request, "Pedido marcado como enviado co msucesso")
        return redirect(pedido.get_absolute_url())

class ItemCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'pedidos/item_form.html'
    model = Item
    form_class = ItemForm
    success_message = 'Item adicionado com sucesso!'
    
    def dispatch(self, request, *args, **kwargs):
        self.pedido = Pedido.objects.get(id=self.kwargs["pedido"])
        if self.pedido.status == Pedido.CRIADO:
            return super().dispatch(request, *args, **kwargs)
        messages.error(request, "Esse pedido não pode mais ser alterado")
        return redirect(self.pedido.get_absolute_url())
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.pedido = self.pedido
        item.valor_base = item.produto.valor
        item.subtotal = item.valor_base * item.quantidade
        item.save()
        item.pedido.update_total()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(item.pedido.get_absolute_url())
    
class PodeModificarPedidoItemMixin(object):
    def dispatch(self, request, *args, **kwargs):
        self.pedido = self.get_object(self.queryset).pedido
        if self.pedido.status == Pedido.CRIADO:
            return super().dispatch(request, *args, **kwargs)
        messages.error(request, "Esse pedido não pode mais ser alterado")
        return redirect(self.pedido.get_absolute_url())
        
        
class ItemUpdateView(LoginRequiredMixin, SuccessMessageMixin, PodeModificarPedidoItemMixin, UpdateView):
    template_name = 'pedidos/item_form.html'
    model = Item
    form_class = ItemForm
    success_message = 'Item atualizado com sucesso!'
    
    def form_valid(self, form):
        item = form.save(commit=False)
        item.subtotal = item.valor_base * item.quantidade
        item.save()
        item.pedido.update_total()
        messages.success(self.request, self.success_message)
        return HttpResponseRedirect(item.pedido.get_absolute_url())
    
class ItemDeleteView(LoginRequiredMixin, SuccessMessageMixin, PodeModificarPedidoItemMixin, DeleteView):
    template_name = 'pedidos/item_delete.html'
    model = Item
    success_url = reverse_lazy('pedido__list')
    success_message = 'Item excluido com sucesso!'

apps/pedidos/templates/pedidos/item_delete.html
{% extends 'base/base_delete.html' %}

{% block model_name %}Item{% endblock model_name %}
{% block model_name__text %}Item{% endblock model_name__text %}
{% block model %}{{ object.produto.nome }} do Pedido # {{ object.pedido.pk }} - {{ object.pedido.cliente.nome}}{% endblock model %}

apps/pedidos/templates/pedidos/item_form.html
{% extends 'base/base_form.html' %}

{% block form__name %}Item{% endblock form__name %}
{% block form__header %}Item{% endblock form__header %}

apps/pedidos/templates/pedidos/pedido_delete.html
{% extends 'base/base_delete.html' %}

{% block model_name %}Pedido{% endblock model_name %}
{% block model_name__text %}Pedido{% endblock model_name__text %}
{% block model %}# {{ object.pk }} - {{ object.cliente.nome}}{% endblock model %}

apps/pedidos/templates/pedidos/pedido_detail.html
{% extends 'base/base_sistema.html' %}

{% block title %} Pedido - {{ object.cliente.nome }} {% endblock title %}

{% block conteudo__header__text %}
   Pedido # {{ object.pk }} - {{ object.cliente.nome}}
{% endblock conteudo__header__text %}

{% block conteudo__header_actions %}

    {% if object.status == 'CRD' %}
        <button class="btn btn-primary" onClick="confirmarAcao('Tem certeza que deseja fechar o pedido?', '{% url 'pedido__fechar' object.pk %}')">Fechar</button>
        <a href="{{ object.get_add_item_url }}" class="btn btn-success">Adicionar Produto</a>
        <a href="{{ object.get_update_url }}" class="btn btn-primary">Atualizar</a>
        <a href="{{ object.get_delete_url }}" class="btn btn-danger">Excluir</a>

    {% elif object.status == 'FCD' %}
        <button class="btn btn-primary" onClick="confirmarAcao('Tem certeza que deseja marcar o pedido como enviado?', '{% url 'pedido__enviar' object.pk %}')">Marcar como enviado</button>
    {% endif %}

{% endblock conteudo__header_actions %}


{% block conteudo %}

<form action="" method="POST" id="id_form">{% csrf_token %}</form>
    
    <p><b>Data:</b> {{object.data|date:"d/m/Y"}}</p>
    <p><b>Status:</b> {{object.get_status_display}}</p>
    <p><b>Total:</b>R$ {{object.total}}</p>

    <h3>Itens</h3>
    <table class="table table-hover">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                    <th>Unidade</th>
                    <th>Valor Base</th>
                    <th>Subtotal</th>
                    {% if object.status == 'CRD' %}
                        <th style="width: 15%;">Ações</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                 {% for item in object.get_itens %}
                 
                 <tr>
                    <td>{{ item.produto.nome }}</td>
                    <td>{{ item.quantidade }}</td>
                    <td>{{ item.produto.get_unidade_display }}</td>
                    <td>R$ {{ item.valor_base }}</td>
                    <td>{{ item.subtotal }}</td>
                    {% if object.status == 'CRD' %}
                    <td>
                        <a href="{{ item.get_update_url }}" class="btn btn-primary">Atualizar</a>
                        <a href="{{ item.get_delete_url }}" class="btn btn-danger">Excluir</a>
                    </td>
                    {% endif %}
                    
                 </tr>
                 
                 {% endfor %}
                 <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>R$ {{ object.total }}</td>
                    {% if object.status == 'CRD' %}
                    <td></td>
                    {% endif %}
                 </tr>
            </tbody>
            </table>

<script>
    var form = document.getElementById("id_form");
    function confirmarAcao(mensagem, url){
        if(confirm(mensagem)){
            form.action = url;
            form.submit();
        }
    }
</script>

{% endblock conteudo %}

apps/pedidos/templates/pedidos/pedido_form.html
{% extends 'base/base_form.html' %}

{% block form__name %}Pedidos{% endblock form__name %}
{% block form__header %}Pedidos{% endblock form__header %}

apps/pedidos/templates/pedidos/pedido_list.html
{% extends 'base/base_list.html' %}

{% block list_title__model_name %}Pedidos{% endblock list_title__model_name %}
{% block conteudo__header__text %}Pedidos{% endblock conteudo__header__text %}
{% block botao_add__url %}{% url 'pedido__cria' %}{% endblock botao_add__url %}


{% block before_table %}
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if CRIADO %}active{% endif %}" href="{% url 'pedido__list' %}">Criados</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if FECHADO %}active{% endif %}" href="{% url 'pedido__list__fechado' %}">Fechados</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if ENVIADO %}active{% endif %}" href="{% url 'pedido__list__enviado' %}">Enviados</a>
        </li>
    </ul>
{% endblock before_table %}



{% block lista__header %}
    <tr>
        <th scope="col">Cliente</th>
        <th scope="col">Data</th>
        <th scope="col">Total</th>
    </tr>
{% endblock lista__header %}

{% block lista %}
    {% for pedido in object_list %}
    <tr onclick="to('{{ pedido.get_absolute_url }}')">
        <td>{{ pedido.cliente.nome }}</td>
        <td>{{ pedido.data|date:"d/m/Y" }}</td>
        <td>R$ {{ pedido.total }}</td>
    </tr>
    {% endfor %}

{% endblock lista %}

apps/pedidos/templates/pedidos/pedidos.html
{% extends 'base/base_sistema.html' %}
{% block title %}
    Sistema
{% endblock title %}
{% block conteudo %}

    <h1>Sistema </h1>
{% endblock conteudo %}